# Generated by Django 3.0.3 on 2021-01-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80, verbose_name='TITLE'),
        ),
    ]
